server:
  port: 5000
spring:
  local:
    dir: C:/Users/ahakim/Dev/github/s3-upload/tmp
  profiles:
    Default: local
  devtools:
    livereload:
      enabled: true
  servlet:
    multipart:
      maxFileSize: 1GB
      maxRequestSize: 5GB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/test?&serverTimezone=UTC&autoReconnect=true&allowMultiQueries=true&characterEncoding=UTF-8
    username: web
    password: web
    hikari:
      maximum-pool-size: 5
      jdbc-url: ${spring.datasource.url}
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      driver-class-name: ${spring.datasource.driver-class-name}
# MyBatis
mybatis:
  type-aliases-package: io.ahakim.file.domain
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
# jasypt
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
# AWS S3
aws:
  s3:
    bucket: ahakim-s3-bucket
    region:
      static: ap-northeast-2
    credentials:
      accessKey: ENC(O7bemcJ9F6ASOyV865LbMDRZALiBbRwBLLmBEX6I63s=)
      secretKey: ENC(FjOotJO8ljSJYnc6Ytzzu8xgbMwAHvIg+J8QY9rz3eRvd1n6Zew9yjt/XhE/lsOu8NjdpNP7mmw=)
    stack:
      auto: false